name: designchallenge
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  dotted_border: ^1.0.5
  clip_shadow: ^0.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BrandonGrotesque-Black
      fonts:
        - asset: assets/fonts/BrandonGrotesque-Black.ttf
    - family: ProximaNova-Regular
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
    - family: ProximaNova-Light
      fonts:
        - asset: assets/fonts/ProximaNova-Light.ttf
    - family: ProximaNova-Semibold
      fonts:
        - asset: assets/fonts/ProximaNova-Semibold.ttf
    - family: MyriadPro-Bold
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.ttf
    - family: MyriadPro-Regular
      fonts:
        - asset: assets/fonts/MyriadPro-Regular.ttf
    - family: HelveticaNeue-Medium
      fonts:
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
    - family: MuseoSans-100
      fonts:
        - asset: assets/fonts/MuseoSans-100.ttf
    - family: MuseoSans-300
      fonts:
        - asset: assets/fonts/MuseoSans-300.ttf
    - family: Futura-Heavy
      fonts:
        - asset: assets/fonts/Futura-Heavy.ttf
    - family: Futura-Light
      fonts:
        - asset: assets/fonts/Futura-Light.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
    - family: LatoBlack
      fonts:
        - asset: assets/fonts/LatoBlack.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fonts/LatoBold.ttf
    - family: LatoLightItalic
      fonts:
        - asset: assets/fonts/LatoLightItalic.ttf
    - family: DINPro-Bold
      fonts:
        - asset: assets/fonts/DINPro-Bold.ttf
    - family: DINPro-BoldItalic
      fonts:
         - asset: assets/fonts/DINPro-BoldItalic.ttf
    - family: DINPro-Italic
      fonts:
         - asset: assets/fonts/DINPro-Italic.ttf
    - family: DINPro-Light
      fonts:
         - asset: assets/fonts/DINPro-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
